title: Suki Tsubaki
description: Personal Blog & Website
author: Suki Tsubaki

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

# Plugins (minimal for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Prevent caching in the browser
headers:
  - Cache-Control: no-cache, no-store, must-revalidate
  - Pragma: no-cache
  - Expires: 0

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
